### ISSUE TITLE
vuduo2 build fails due to python-mutagen md5 checksum mismatch

### ISSUE THREAD

**Issue by tomparkin** [OpenPLi/openpli-oe-core#116]
I'm working on master, commit a3b982d

During fetching of sources the vuduo2 build fails:

> ERROR: Fetcher failure for URL: 'http://pkgs.fedoraproject.org/repo/pkgs/python-mutagen/mutagen-1.18.tar.gz/0c2cd954e4bacd79fadd45afc4acce4c/mutagen-1.18.tar.gz'. Checksum mismatch!
> File: '/home/foobar/openpli-oe-core/sources/mutagen-1.18.tar.gz' has md5 checksum 0c2cd954e4bacd79fadd45afc4acce4c when ${MD5SUM} was expected

The recipe for mutagen sets SRC_URI[md5sum] like this:

```
MD5SUM = "0c2cd954e4bacd79fadd45afc4acce4c"
SRC_URI[md5sum] = "${MD5SUM}"
```

... which seems to stem from commit a21f673, and was probably motivated by the fact that the download URI for the source contains the checksum in the path, so rather than write it out twice a variable is used.  However it seems that when setting SRC_URI[md5sum] the variable isn't evaluated as expected -- I don't know enough about bitbake to fully understand why not.

I have a naive patch which Works For Me, perhaps there is a more elegant solution though:

```
From 266d2cf38975e36fb93f321dda5e7c603ff11e72 Mon Sep 17 00:00:00 2001
From: Tom Parkin <redacted>
Date: Wed, 19 Oct 2016 14:51:04 +0100
Subject: [PATCH] meta-openpli: fix python-mutagen md5 checksum failure on
 download

---
 meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb | 6 ++----
 1 file changed, 2 insertions(+), 4 deletions(-)

diff --git a/meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb b/meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb
index 18e8025..e0ac554 100644
--- a/meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb
+++ b/meta-openpli/recipes-devtools/python/python-mutagen_1.18.bb
@@ -8,13 +8,11 @@ PR = "r1"
 DEPENDS = "python"
 RDEPENDS_${PN} = "python-shell"

-MD5SUM = "0c2cd954e4bacd79fadd45afc4acce4c"
-
-SRC_URI = "http://pkgs.fedoraproject.org/repo/pkgs/${PN}/${SRCNAME}.tar.gz/${MD5SUM}/${SRCNAME}.tar.gz \
+SRC_URI = "http://pkgs.fedoraproject.org/repo/pkgs/${PN}/${SRCNAME}.tar.gz/0c2cd954e4bacd79fadd45afc4acce4c/${SRCNAME}.tar.gz \
    file://patch.diff \
 "

-SRC_URI[md5sum] = "${MD5SUM}"
+SRC_URI[md5sum] = "0c2cd954e4bacd79fadd45afc4acce4c"
 SRC_URI[sha256sum] = "30b6147baf59ab3609939acf49a1a1c73b15d8b1c637a01bfee89da7feea0d6c"

 S = "${WORKDIR}/${SRCNAME}"
-- 
1.9.1
```

**Comment by tomparkin** [comment]
I have created a pull request #117.  I forked the repository in order to do so, let me know if you'd prefer something different instead.

**Comment by athoik** [comment]
please close issue, it is solved.
